import { getImage } from "astro:assets";
import type { ImageMetadata } from "astro";
import mosaicItems from "../data/mosaic-items.json";

export type Photo = (typeof mosaicItems)[number];

// Every photo lives in src/_resources/images-web (gitignored, generated by
// scripts/convert-images-to-webp.bat). The `src` strings in the data files are
// only lookup keys - matched by file name - so the JSON stays human-editable
// while Astro still fingerprints and optimizes the real files at build time.
const files = import.meta.glob<ImageMetadata>("../_resources/images-web/*.{webp,jpg,jpeg,png}", {
  eager: true,
  import: "default",
});
const byName = new Map(Object.entries(files).map(([path, image]) => [path.split("/").pop(), image]));

export function imageFor(src: string): ImageMetadata {
  const image = byName.get(src.split("/").pop());
  if (!image) throw new Error(`[photos] "${src}" not found in src/_resources/images-web`);
  return image;
}

const byId = new Map(mosaicItems.map((item) => [item.id, item]));

export function photoById(id: string): Photo {
  const item = byId.get(id);
  if (!item) throw new Error(`[photos] unknown photo id "${id}" (see src/data/mosaic-items.json)`);
  return item;
}

export const allPhotos: Photo[] = mosaicItems;

// `thumb` is sized for grid/mosaic tiles (2x a 220-240px row), `src` is the
// full size (already capped at 1600px by the conversion script; re-encoded at
// high quality because Astro only emits originals it sees used in markup),
// `srcset` adds a medium size for the lightbox.
export async function photoVariants(item: Photo) {
  const image = imageFor(item.src);
  const [thumb, medium, full] = await Promise.all([
    getImage({ src: image, height: 480 }),
    getImage({ src: image, width: Math.min(1024, image.width) }),
    getImage({ src: image, width: image.width, quality: 90 }),
  ]);
  return {
    ...item,
    thumb: thumb.src,
    src: full.src,
    srcset: `${medium.src} ${medium.attributes.width ?? 1024}w, ${full.src} ${image.width}w`,
    width: image.width,
    height: image.height,
    aspect: Number((image.width / image.height).toFixed(4)),
  };
}

export type PhotoVariants = Awaited<ReturnType<typeof photoVariants>>;
